spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:/mysql:/localhost:3306/Healthcare_managment_system
    password: Alice@123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true