CREATE SEQUENCE IF NOT EXISTS appointment_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS clinics_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS doctors_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS medical_record_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS patients_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE appointment
(
    appointment_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    doctor_id        BIGINT                                  NOT NULL,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id       BIGINT,
    notes            VARCHAR(255),
    status           VARCHAR(255)                            NOT NULL,
    CONSTRAINT appointment_pkey PRIMARY KEY (id)
);

CREATE TABLE clinics
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    phone   VARCHAR(255)                            NOT NULL,
    CONSTRAINT clinics_pkey PRIMARY KEY (id)
);

CREATE TABLE doctors
(
    clinic_id  BIGINT,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    firstname  VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    speciality VARCHAR(255)                            NOT NULL,
    CONSTRAINT doctors_pkey PRIMARY KEY (id)
);

CREATE TABLE medical_record
(
    doctor_id    BIGINT,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id   BIGINT,
    record_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    prescription VARCHAR(500),
    diagnosis    VARCHAR(255)                            NOT NULL,
    CONSTRAINT medical_record_pkey PRIMARY KEY (id)
);

CREATE TABLE patients
(
    date_of_birth date                                    NOT NULL,
    clinic_id     BIGINT,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    firstname     VARCHAR(255)                            NOT NULL,
    lastname      VARCHAR(255)                            NOT NULL,
    phone         VARCHAR(255)                            NOT NULL,
    CONSTRAINT patients_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    date_of_birth TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone         VARCHAR(255),
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255),
    password      VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE appointment
    ADD CONSTRAINT appointment_notes_key UNIQUE (notes);

ALTER TABLE clinics
    ADD CONSTRAINT clinics_name_key UNIQUE (name);

ALTER TABLE clinics
    ADD CONSTRAINT clinics_phone_key UNIQUE (phone);

ALTER TABLE doctors
    ADD CONSTRAINT doctors_email_key UNIQUE (email);

ALTER TABLE patients
    ADD CONSTRAINT patients_email_key UNIQUE (email);

ALTER TABLE patients
    ADD CONSTRAINT patients_phone_key UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE appointment
    ADD CONSTRAINT fk3mbue9w5cldlnxx3hm15t5sfo FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE NO ACTION;

ALTER TABLE appointment
    ADD CONSTRAINT fk51y2ce12yp0g0hgsa39p2u9jq FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE NO ACTION;

ALTER TABLE medical_record
    ADD CONSTRAINT fkc0owwx1i1r9xf3h4uxw89rd1l FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE NO ACTION;

ALTER TABLE doctors
    ADD CONSTRAINT fkihqanxookqa5oh9guthqjfxxm FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE NO ACTION;

ALTER TABLE patients
    ADD CONSTRAINT fkm78f4ycelhyuh51u08g20dcmd FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE NO ACTION;

ALTER TABLE medical_record
    ADD CONSTRAINT fkoxhj68goxtsc54fihf9u25l0w FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE NO ACTION;